### PR TITLE
Next_Milestone

### PR DESCRIPTION
**Pull request by sumon0002001**
We create the game flow to get a better understanding of game logic for the next milestone.
-We use ruby comments to make a flow.
-We try to implement the logic from start to finish the game for a player.

### CODE REVIEW

**Review by PhillipUg — COMMENTED** [review]
Hello Team, My name is Phillip Musiime and I will be handling your review.

**Review by PhillipUg — CHANGES_REQUESTED** [review]
# Changes Required! ♻️ 

Hey team, 👋 You have done a *great* job on this project so far, however, we need to make the following changes to fulfill the project requirements before we can move on to the next milestone
## [REQUIRED] 

- [ ] `main.rb` uses `puts/print` and `get.chomp` commands. Implementing a user interface that displays prompt for users (`print/puts`) and collects user input (`get.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no matter who won.

screenshot-gitlab com-2020 10 27-19_44_41

* [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
* [x] `[REQUIRED]` game asks the player to select from available moves
* [ ] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
* [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
* [ ] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
* [x] `[REQUIRED]` game repeats all actions for the next player's move

To achieve this, for example, you can use a loop (e.g **while loop**) and perform the same actions for each player inside the loop. However don't forget, the loop needs to be terminated at some point (after a winning or draw move). The winning or draw can be simulated using a terminating variable (No need to implement winning or draw logic in this milestone).

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as (**Phillip Musiime**)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Phillip Musiime

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

> * [x]  `[REQUIRED]` game asks the player to select from available moves

- [ ] The game should ask the player to select from available moves also when the user input is `invalid`. 

> To achieve this, for example, you can use a loop (e.g **while loop**) and perform the same actions for each player inside the loop. However don't forget, the loop needs to be terminated at some point (after a winning or draw move). The winning or draw can be simulated using a terminating variable (No need to implement winning or draw logic in this milestone).

- [ ] The loop has an ending after the 10th moves regardless if the user has `invalid` choices. The loop should be improved in a way that the only way to end the game is if the game is drawn or if a user has won. Example.

```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
### [OPTIONAL]  :yellow_circle:  

- [ ] The project should follow a structure, that will not implement any logic but will be used as a template for the game flow. Try to show the code in a way that it shows the flow of the game. Example.... (it is just an example of a game flow, not a guide)
```
1. Ask if the user want to play
2. If they don't: end the game
3. If they do: Ask for the users name
4. show the board
5. loop
5.1 player 1 turn
5.2 player 2 turn
6. Check for winner or draw
6.1 a player has won: show message 'You have won' end game
6.2 is a draw, show message 'Both loose' end game
7. ask if they wanna a play.
```
Working on this will make it easier to apply next steps.

- [ ]  The game should prompt for player's information. 

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved.
### Hello Team. :wave: 

Nice work implementing the changes requested by the previous TSE. :clap: 
You have met the requirements for this milestone and can go ahead to merge into development.
### Goodluck with the next milestone :+1: 
slack(@ebeagusamuel)

**Pull request merged**
